language: java
sudo: false # faster builds

jdk:
  - openjdk8
  - openjdk11
  
script:
 - mvn clean install package
 - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
